name: Publish to PyPI

on:
  release:
    types:
      - created

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install build dependencies
      run: pip install build
    - name: Build distribution g2p-payments-bridge-core
      run: python -m build ./g2p-payments-bridge-core
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: g2p-payments-bridge-core/dist
        password: ${{ secrets.PYPI_API_TOKEN }}
    - name: Build distribution gpb-translate-id-fa
      run: python -m build ./gpb-translate-id-fa
    - name: Publish gpb-translate-id-fa
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: gpb-translate-id-fa/dist
        password: ${{ secrets.PYPI_API_TOKEN }}
    - name: Build distribution gpb-simple-mpesa-payment-backend
      run: python -m build ./gpb-simple-mpesa-payment-backend
    - name: Publish gpb-simple-mpesa-payment-backend
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: gpb-simple-mpesa-payment-backend/dist
        password: ${{ secrets.PYPI_API_TOKEN }}
    - name: Build distribution gpb-mojaloop-sdk-payment-backend
      run: python -m build ./gpb-mojaloop-sdk-payment-backend
    - name: Publish gpb-mojaloop-sdk-payment-backend
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: gpb-mojaloop-sdk-payment-backend/dist
        password: ${{ secrets.PYPI_API_TOKEN }}
